version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_APP=manage.py
      - FLASK_CONFIG=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homework_system
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=homework_system
    ports:
      - "5432:5432"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/usr/share/nginx/html/static
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
